import java.awt.*;
import javax.swing.*;

class CalculatorGUI{
 
 
  private JFrame fCalc;
  private JButton b0, b1, b2, b3, b4, b5, b6, b7, b8, b9;
  private JButton bPlus, bMinus, bMul, bPoint, bEqual, bClear;
  private JPanel pButtons;
  private JTextField tfAnswer;
  private JLabel lMyCalc;

  public CalculatorGUI(){
    initGUI();
  } 

   private void initGUI() {
        fCalc = new JFrame("My Calculator");
        fCalc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Initialize buttons
        b0 = new JButton("0");
        b1 = new JButton("1");
        b2 = new JButton("2");
        b3 = new JButton("3");
        b4 = new JButton("4");
        b5 = new JButton("5");
        b6 = new JButton("6");
        b7 = new JButton("7");
        b8 = new JButton("8");
        b9 = new JButton("9");

        bPlus = new JButton("+");
        bMinus = new JButton("-");
        bMul = new JButton("*");
        bPoint = new JButton(".");
        bEqual = new JButton("=");
        bClear = new JButton("C");

        tfAnswer = new JTextField();
        tfAnswer.setEditable(false);

        lMyCalc = new JLabel("My Calculator", JLabel.CENTER);

        // Panel for buttons
        pButtons = new JPanel(new GridLayout(4, 4, 5, 5));
        pButtons.add(b1); pButtons.add(b2); pButtons.add(b3); pButtons.add(bClear);
        pButtons.add(b4); pButtons.add(b5); pButtons.add(b6); pButtons.add(bMul);
        pButtons.add(b7); pButtons.add(b8); pButtons.add(b9); pButtons.add(bMinus);
        pButtons.add(b0); pButtons.add(bPoint); pButtons.add(bPlus); pButtons.add(bEqual);

        // Layout setup
        Container con = fCalc.getContentPane();
        con.setLayout(new BorderLayout(5, 5));
        con.add(tfAnswer, BorderLayout.NORTH);
        con.add(pButtons, BorderLayout.CENTER);
        con.add(lMyCalc, BorderLayout.SOUTH);

        fCalc.setSize(300, 400);
        fCalc.setLocationRelativeTo(null); // center window
        fCalc.setVisible(true);
    }
}
public class Test{
  public static void main(String[] args){
    // CalculatorGUI gui = new CalculatorGUI();
    SwingUtilities.invokeLater(CalculatorGUI::new);
  }
}

//events 
//in java events are objects these tells about event and its source ActionEvent ,WindowEvent 
//public subscribe modle
//-saprete ui code from program logic
//steps for event handling
//step1
//-create a component which can generate an events
//step2
//-build component (object) that can handle events 
//step3
//-register handlers with generators

//event generators 
//mouse ,key ,window, button ets
//event handling process
//eventhandlers //event listners
//First Technique -By Implementing Listener interface
//-java define Interface for every event type
//-if class need to handle any event it needs to impliment the coressponding listner Interface
//-to handle ActionEvent a class need to impliment ActionListner 
//-To handle keyEvent a class needs to impliment KeyListener
//byImplimenting an interface the class agrees to impliment  all mehods present in that interface
//implimenting an interface is like signing a contract
//inside the method a  class can do whatever it wants to do with events 
//event generator and eventhandler can be the same or diffrent classes 
//the handle event generated by a button A class need to impliment ActionListner linerface
//registring handler with generoter 
//the event generator is told about the object which can handle its event
//event Generator have a method 

